package com.gemini.compiler.ast;

/**
 * AST 节点类型枚举
 */
public enum ASTNodeType {
    // 程序结构
    PROGRAM,
    
    // 声明
    STRUCT_DECLARATION,
    FUNCTION_DECLARATION,
    VARIABLE_DECLARATION,
    PARAMETER,
    
    // 语句
    BLOCK,
    EXPRESSION_STATEMENT,
    IF_STATEMENT,
    WHILE_STATEMENT,
    FOR_STATEMENT,
    SWITCH_STATEMENT,
    CASE_STATEMENT,
    DEFAULT_STATEMENT,
    BREAK_STATEMENT,
    CONTINUE_STATEMENT,
    RETURN_STATEMENT,
    
    // 表达式
    ASSIGNMENT_EXPRESSION,
    CONDITIONAL_EXPRESSION,
    LOGICAL_OR_EXPRESSION,
    LOGICAL_AND_EXPRESSION,
    EQUALITY_EXPRESSION,
    RELATIONAL_EXPRESSION,
    ADDITIVE_EXPRESSION,
    MULTIPLICATIVE_EXPRESSION,
    UNARY_EXPRESSION,
    POSTFIX_EXPRESSION,
    PRIMARY_EXPRESSION,
    CAST_EXPRESSION,
    
    // 字面量和标识符
    IDENTIFIER,
    INT_LITERAL,
    FLOAT_LITERAL,
    CHAR_LITERAL,
    STRING_LITERAL,
    
    // 类型
    TYPE,
    
    // 函数调用
    FUNCTION_CALL,
    ARGUMENT_LIST,
    
    // 数组访问
    ARRAY_ACCESS,
    
    // 结构体成员访问
    MEMBER_ACCESS
}